# Generated by Django 2.2.14 on 2020-12-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Enter field documentation', max_length=200)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('autor', models.CharField(help_text='Enter field documentation', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('tags', models.ManyToManyField(related_name='tags', to='tags.Tag')),
            ],
        ),
    ]
