# Generated by Django 2.2.14 on 2020-12-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
